import {
  AlertTriangle,
  BarChart3,
  ChevronDown,
  ChevronRight,
  Circle,
  Copy,
  Download,
  File,
  GripVertical,
  Lock,
  Minus,
  Monitor,
  Moon,
  Plus,
  RotateCcw,
  Settings,
  Sun,
  Target,
  Trash2,
  Unlock,
  Upload,
  User,
  Users,
  X,
  MapPin
} from 'lucide-react'

export const iconMap = {
  add: Plus,
  remove: Minus,
  close: X,
  delete: Trash2,
  settings: Settings,
  duplicate: Copy,
  lock: Lock,
  unlock: Unlock,
  themeLight: Sun,
  themeDark: Moon,
  themeAuto: Monitor,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  dragHandle: GripVertical,
  skills: Target,
  skillLevels: BarChart3,
  export: Download,
  import: Upload,
  reset: RotateCcw,
  templateStandard: User,
  templateQuick: Users,
  templateScene: MapPin,
  templateBlank: File,
  aspectBullet: Circle,
  fatePoint: Circle,
  warning: AlertTriangle
}
